#cloud-config

groups:
  - debian-tor

packages:
  - tor
  - torsocks
  - obfs4proxy

runcmd:
  - setcap 'cap_net_bind_service=+ep' /usr/bin/obfs4proxy
  - sed -i "s/^NoNewPrivileges=yes/NoNewPrivileges=no/g" /lib/systemd/system/tor@{,default}.service
  - systemctl daemon-reload && systemctl restart tor

system_info:
  default_user:
    groups:
      - debian-tor
